library(shiny)
library(bslib)
library(ggplot2)
library(dplyr)
library(dbplyr)

source('logic/build_quack_db.R')
#data(penguins, package = "palmerpenguins")

#
# color_by <- varSelectInput(
#   "color_by", "Color by",
#   penguins[c("species", "island", "sex")],
#   selected = "species"
# )


about_description <- "**Description of a Shiny App for Testing SQL Generation with dbplyr:**

The Shiny app serves as a demonstration platform for testing SQL generation using the `dbplyr` package. This app is designed to showcase the capabilities of creating dynamic SQL queries in a Shiny environment, utilizing the power of `dbplyr` to interact with databases.

**Key Features:**

1. **Database Connection Setup:**
   - Users can establish a connection to a database of their choice by providing the necessary credentials and connection details.
   - The app supports various database systems, including but not limited to MySQL, PostgreSQL, SQLite, and more.

2. **SQL Query Generation:**
   - Users have the ability to construct SQL queries dynamically using an intuitive interface.
   - The app demonstrates the process of translating high-level operations written in R using `dbplyr` functions into equivalent SQL queries.

3. **Query Execution:**
   - Once a query is constructed, users can execute it against the connected database and view the results within the app.
   - The app showcases how `dbplyr` efficiently converts R-based data manipulation commands into SQL statements and retrieves the results.

4. **Visualization of Generated SQL:**
   - The app provides a dedicated section to display the SQL code that corresponds to the constructed `dbplyr` query.
   - This feature aids users in understanding the translation between R-based data manipulation and the underlying SQL commands.

5. **Interactive Exploration:**
   - Users can experiment with different `dbplyr` functions, such as `filter`, `select`, `mutate`, etc., and observe how these operations are translated into SQL statements.
   - The interactive nature of the app allows users to gain a hands-on understanding of how to harness the power of `dbplyr` for SQL generation.

**Use Case Scenarios:**

- **Educational Tool:** Ideal for individuals learning about database interactions in R and the translation of R commands into SQL using `dbplyr`.

- **Development Aid:** Useful for developers working on projects involving database interactions, providing a sandbox environment to test and optimize SQL queries.

- **Debugging Resource:** Acts as a diagnostic tool for debugging and validating the SQL code generated by `dbplyr` during the development phase.

- **Training Platform:** Can be used in training sessions or workshops to illustrate the seamless integration of R and SQL for database operations.

**Note:** Ensure that users are cautious with sensitive data and have the necessary permissions to interact with the chosen database system. The app's primary goal is to facilitate learning and testing, not for production use with critical databases."

quack_db <- generate_nyflights_demo_db()

nyflights_tbl <- tbl(quack_db, "flights")

destinations <- nyflights_tbl |>
  distinct(dest) |>
  collect() |>
  arrange() |>
  pull()

# destination_by <- varSelectInput(
#   "destination_by",
#   "Destinations from NY",
#   destinations,
#   selected = "ATL"
# )

cards <- list(
  card(
    full_screen = TRUE,
    card_header("Monthly Flight Count Over Time"),
    plotOutput("monthly_flight_count_plot")
  ),
  card(
    full_screen = TRUE,
    card_header("Distribution of Flights by Carrier"),
    plotOutput("distribution_of_delayed_flights_plot")
  ),
  card(
    full_screen = TRUE,
    card_header("Average Departure Delay by Carrier"),
    plotOutput("avg_dep_delay_by_carrier_plot")
  )
)

ui <- page_sidebar(
  fillable = FALSE,
  title = "NY City Airports Dashboard",
  sidebar = selectInput(
    "destination_by",
    "Destinations from NY",
    choices = destinations,
    selected = "ATL"
  ),
  theme = bs_theme(
    bootswatch = "darkly",
    base_font = font_google("Inter"),
    navbar_bg = "#25443B"
  ),
  navset_card_underline(
    title = "Tools",
    nav_panel("Data View", !!!cards),
    nav_panel("SQL",
              fluidRow(
                column(
                  width = 6,
                  verbatimTextOutput("generated_sql")
                ),
                column(
                  width = 6,
                  tags$iframe(
                    seamless = "seamless",
                    src = "https://tidydatatutor.com/vis.html#code=library%28dplyr%29%0Alibrary%28palmerpenguins%29%0A%0Aset.seed%282021-12-03%29%0A%0Asample_penguins%20%3C-%20penguins%20%25%3E%25%0A%20%20group_by%28species%29%20%25%3E%25%20%0A%20%20sample_n%283%29%20%25%3E%25%20%0A%20%20select%28species,%20bill_length_mm%29%0A%0Asample_penguins%20%25%3E%25%20%0A%20%20arrange%28bill_length_mm,%20.by_group%20%3D%20TRUE%29&d=2023-12-19&lang=r&v=v1",
                    height = 800,
                    width = 1400
                  )
                )
              )
            ),
    nav_panel("About",
              markdown(about_description)
              )
  )
)


server <- function(input, output) {

  analyzed_flights <- reactive({
    req(input$destination_by)
    nyflights_tbl |>
      analyze_flights_data(input$destination_by)
  })


  output$avg_dep_delay_by_carrier_plot <- renderPlot({
    visualize_avg_dep_delay_by_carrier(analyzed_flights()$avg_dep_delay_by_carrier)
  })

  output$monthly_flight_count_plot <- renderPlot({
    visualize_monthly_flight_count(analyzed_flights()$flight_count_by_month)
  })


  # observe({
  #   print(analyzed_flights()$filtered_dataset)
  # })

  output$distribution_of_delayed_flights_plot <- renderPlot({
    visualize_distribution_of_flights_by_delayed_status(analyzed_flights()$filtered_dataset)
  })

  output$generated_sql <- renderText({
    analyzed_flights()$filtered_data_sql
  })

}


shinyApp(ui, server)
